### ISSUE TITLE
Вылет mdNavigator после загрузки конфигурации

### ISSUE THREAD

**Issue by 7OH** [infostart-hub/snegopat#105]
**Описание ошибки**
После загрузки конфигурации из файла (или объединения) с получением объектов - навигатор по метаданным не находит новые объекты. 
Или падает при попытке обновить.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создаём пустую базу
2. Загружаем конфиг, сохраняем (но не ф7)
3. Открываем навигатор по метаданным - при поиске ничего не находит
4. При нажатии на обновить в окне скрипта - ошибка

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/3063507/99889066-939ab300-2c5a-11eb-9343-e9d5aff32f48.png)

**Окружение:**

   - Платформа 1С:  8.3.17.1851, 8.3.18.1208

**Comment by artbear** [comment]
выполнено в https://github.com/infostart-hub/snegopat/pull/106
