### ISSUE TITLE
Аддин Расширенный поиск и замена. Ошибка перехода к строке

### ISSUE THREAD

**Issue by nonameformr** [infostart-hub/snegopat#112]
**Описание ошибки**
Не переходит к найденной строке

**Ожидаемое поведение, если бы ошибки не было**
Переход к конкретной строке

**Скриншоты**
![image_2020-12-09_15-03-28](https://user-images.githubusercontent.com/11997188/101748023-13d76a00-3add-11eb-8df3-c2b867933fc1.png)

**Окружение:**
[2.2.0.4 | 8.3.13.1644 | 21 ноября 2020 г. 14:46:56]

Семён Павлюков, [09.12.20 16:01]
[В ответ на Dmitriy 🌏]
сделайте в гите задачу - поиск слова целиком идёт через regExp - надо видимо экранировать спецсимволы
в общем доработка нужна

**Comment by artbear** [comment]
Выполнено.
