### ISSUE TITLE
Расположение temp, bls-ls-cfg + ошибки для выделенного кода.

### ISSUE THREAD

**Issue by BProg-Gladkov** [infostart-hub/snegopat#114]
**Существует проблема**
1. Пользователь у которого в имени есть русские буквы не может использовать свой каталог временных файлов.
BSL-LS не работает с русскими буквами в пути.
2. При проверке кода применяются настройки  BSL-LS по умолчанию.
В некоторых проектах требуется отключить часть проверок.
Для этого необходимо, что бы можно было указать путь к конфигурационному файлу.
3. При доработке больших модулей проверка отображает большое количество ошибок.
Требуется возможность отображения ошибок только для выбранной части кода.

**Хотелось бы иметь следующую функциональность**
1. Предоставить возможность указать произвольный путь к каталогу в котором будут создаваться временные файлы.
2. Предоставить возможность указать путь к конфигурационному файлу.
3. Если выделено более чем одна строка кода отображать ошибки только для выделенного фрагмента кода.

**Comment by artbear** [comment]
выполнено.
