### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#18]
<b>plnz</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=910&sid=862fe2d95b7edac67918c713f3b8aee8#p11661">Ошибка при запуске</a>
Последняя версия снегопата. При запуске конфигуратора такие ошибки.<br/>
<br/>
<b>Вложения:</b><img alt="2020-09-15_08-37-08.png" src="https://snegopat.ru/forum/download/file.php?id=1062&amp;sid=862fe2d95b7edac67918c713f3b8aee8"/>
<hr/>
<b>plnz</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=910&sid=862fe2d95b7edac67918c713f3b8aee8#p11662">Re: Ошибка при запуске</a>
По ошибке отбой. Запускал тестовую сборку.<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
закрыто, т.к пользователь написал отбой
