### ISSUE TITLE
[2.2.0.3 | 8.2.15,16 | 21.07.2020] Пропадает окно подсказки

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#19]
<b>shmalevoz</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=863&sid=862fe2d95b7edac67918c713f3b8aee8#p11568">[2.2.0.3 | 8.2.15,16 | 21.07.2020] Пропадает окно подсказки</a>
В длинных модулях, примерно > 2000 строк при перемещении в окне подсказки клавишами Up Down окно подсказки пропадает<br/>При вызове окна по Ctrl+Пробел пропадает реже, но тоже случается<br/><img alt="Изображение" src="https://s7.gifyu.com/images/snegopat-updown-error.gif"/><br/>
<br/>
<b>Вложения:</b>
<hr/>
<b>shmalevoz</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=863&sid=862fe2d95b7edac67918c713f3b8aee8#p11596">Re: [2.2.0.3 | 8.2.15,16 | 21.07.2020] Пропадает окно подска</a>
Дополню. Размер модуля на самом деле значения не имеет. Исчезновение списка выбора происходит при нажатии вверх/вниз если отображается контекстная подсказка по методу (желтое всплывающее окошко где выдается описание вызываемого метода)<br/>Если убрать контекстную подсказку (Сервис - Параметры - Модули - Контекстная подсказка, снять с "Автоматическая подсказка при наборе "(" и "."), то без подсказки все ок<br/>
<br/>
<b>Вложения:</b>
<hr/>
<b>tormozit</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=863&sid=862fe2d95b7edac67918c713f3b8aee8#p11660">Re: [2.2.0.3 | 8.2.15,16 | 21.07.2020] Пропадает окно подска</a>
У меня такая же проблема. Довольно неприятная она. Отключил подсказку снегопата в итоге но не только из-за этого бага.<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
Уже исправлено.
