### ISSUE TITLE
Не работает в УПП 1.2 и ЗУП КОРП 3.1

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#35]
<b>vsuh</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=877&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11613">Не работает в УПП 1.2 и ЗУП КОРП 3.1</a>
upd. странно, но на тестовом кластере, на всех конфигурациях Снегопат запустился без ошибок..<br/><br/>[2.2.0.3 | 8.3.15.1700 | 18 августа 2020 г. 15:01:15]<br/>при запуске конфигурации УПП 1.3 сильно потоптанной Акселотом и ЗУП КОРП 3.1 почти не испорченной показывает<br/>--- Ошибка ---<br/>Исключение AngelScript.<br/>модуль: Snegopat<br/>секция: com_metadata.as<br/>функция: IMDContainer@ getIBMDCont()<br/>строка: 782<br/>   Null pointer access<br/>--- Информация ---<br/>Bad AngelScript result code in ScriptToUnknownWrap::one_func<br/>----------------<br/>если потом пытаться жмакать на любой контрол в конфигураторе , то добавляет в лог<br/>--- Ошибка ---<br/>Исключение AngelScript.<br/>модуль: Snegopat<br/>секция: com_events.as<br/>функция: void transmitCommandTrap(ICommandReceiver&inout, const CommandRef@, bool)<br/>строка: 194<br/>   Null pointer access<br/>--- Информация ---<br/>Bad AngelScript result code in callAs<br/><br/>--- Ошибка ---<br/>Исключение AngelScript.<br/>модуль: Snegopat<br/>секция: com_events.as<br/>функция: void transmitCommandTrap(ICommandReceiver&inout, const CommandRef@, bool)<br/>строка: 194<br/>   Null pointer access<br/>--- Информация ---<br/>Bad AngelScript result code in callAs<br/>
<br/>
<b>Вложения:</b>
<hr/>
<b>vsuh</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=877&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11619">Re: Не работает в УПП 1.2 и ЗУП КОРП 3.1</a>
Не утерпел.<br/>Переустановил windows. snegopat заработал.<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
закрываю, уже работает
