### ISSUE TITLE
Ошибка в скрипте "Навигатор по метаданным"

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#36]
<b>nytlenc</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=872&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11602">Ошибка в скрипте "Навигатор по метаданным"</a>
При открытии скрипта "Навигатор по метаданным - Открыть объект метаданных" все отрабатывает корректно.<br/>В дальнейшем при работе с этой же базой скрипт работать перестает и все время выдает ошибку.<br/>Работать начинает корректно только после перезапуска конфигуратора вместе со снегопатом.<br/>Состояние репозитария: [2.2.0.3 | 8.3.15.1958 | 29 июля 2020 г. 10:45:00]<br/>
<br/>
<b>Вложения:</b><img alt="Безымянный.png" src="https://snegopat.ru/forum/download/file.php?id=1027&amp;sid=d281cbbb90ecad8d578a7d48c7a417d3"/>
<hr/>
<b>nytlenc</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=872&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11618">Re: Ошибка в скрипте "Навигатор по метаданным"</a>
 m <a class="postlink" href="https://yadi.sk/i/PJ79oFm_2oKFzw">https://yadi.sk/i/PJ79oFm_2oKFzw</a> m  - GIF-ка как воспроизвести - нужно найти любой объект МД, затем что-то поменять и вернуться к конфигурации БД, после этого скрипт ломается.<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
Исправлено в 2.2.0.4
нужно проверить.

**Comment by artbear** [comment]
подтвердили, что исправлено.
