### ISSUE TITLE
Несколько конфигураторов (или предприятий)

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#40]
<b>nonameforme</b>
<a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=867#p11591">Несколько
    конфигураторов (или предприятий)</a>
[2.2.0.3 | 8.3.13.1644 | 29 июля 2020 г. 10:45:00]<br /><br />Решил создать
отдельную тему и объединить сообщения (для удобства)<br /><br />первое l
<a class="postlink-local" href="https://snegopat.ru/forum/viewtopic.php?p=11569#p11569">viewtopic.php?p=11569#p11569</a>
l <br />второе l
<a class="postlink-local" href="https://snegopat.ru/forum/viewtopic.php?p=11588#p11588">viewtopic.php?p=11588#p11588</a>
l <br /><br />При обычном вводе текста. Открыто несколько Конфигураторов со
Снегопатом<br /><br />
<div>
    <div>
        <b><a href="#" onclick="return false;"><img alt="" border="0" height="9"
                    src="styles/prosilver/imageset/icon_plus_1.gif" width="9" /></a>
            log</b>
    </div>
</div>
<br />

<pre>
--- Ошибка ---
Исключение AngelScript.
модуль: Snegopat
секция: intellisite.as
функция: bool IntelliSite::show(TextWnd@, const string&inout, const string&inout = "", bool = true)
строка: 189
1C version 8.3.13.1644. Snegopat 2.2.0.3 (16.07.2020 20:07)
Exception 0xC0000094 at address 0x028DDC83 (snegopat.dll) in call native func SmartBoxWindow::navigate
Section: intellisite.as
Function: bool IntelliSite::show(TextWnd@, const string&inout, const string&inout = "", bool = true)
Line: 189
Callstack:
ModuleTextProcessor.as : void ModuleTextProcessor::activateInModule(TextWnd@, const string&in, TextPosition&inout, ActivateModes, uint16), line 391,9
ModuleTextProcessor.as : void ModuleTextProcessor::afterChar(TextWnd@, uint16), line 156,13
textwnd.as : void TextWnd::afterChar(uint16), line 548,9
textwnd.as : void DispatchMessagesTrap(MSG&inout, uint), line 402,13
This object at 0x3E69A220:
smartBox = native object 'SmartBoxWindow' (0x3DDA5F90)
itemsGroup = native object 'array' (0x3A5B8F00)
buffe
--- Информация ---
Bad AngelScript result code in callAs
</pre>

<br />
<hr />
<b>nonameforme</b>
<a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=867">Re: Несколько
    конфигураторов (или предприятий)</a>
кстати, для запуска использую
<a class="postlink"
    href="https://helpme1c.ru/obnovlyator-1s-gruppovoe-paketnoe-obnovlenie-vsex-baz-za-odin-raz">Обновлятор 1С</a>,
может он не корректно отрабатывает открытие Предприятия со Снегопатом<br />
<br />
<b>Вложения:</b>
<hr />
<b>7OH</b>
<a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=867#p11599">Re: Несколько
    конфигураторов (или предприятий)</a>
Попробовал одновременный запуск файловой и серверной базы - подсказка где
надо.<br />Если обе серверные - баг есть.<br />При наличии 3-х конфигураторов -
не получается воспроизвести.<br />Так же не при каждой паре версий
получается.<br />Например 15 и 16 - бага нет, а 15 и 17 - стабильно<br />
<br />
<b>Вложения:</b>

**Comment by kuntashov** [comment]
Переписка в чате начиная с https://t.me/snegopat_chat/4337

Сытько Сергей, [07.10.20 12:26]
Кто как решает работу 2 конфигураторов ?
Как угомонить снегопат ко второму конфигуратору инжектится ?

Vp, [07.10.20 12:27]
[In reply to Сытько Сергей]
Закрыть один из них)

Семён Павлюков, [07.10.20 12:28]
Сашу слёзно просить поправить это .
Кому-то вроде помагает открытие третьего.
Как вариант открывать снег для 2-х пустых баз в начале

Сытько Сергей, [07.10.20 12:28]
[In reply to Vp]
а если очень надо сразу два

Семён Павлюков, [07.10.20 12:29]
сейчас наверное и у себя проверю - поможет ли 2 пустых

Сытько Сергей, [07.10.20 12:30]
[In reply to Семён Павлюков]
я пробовал даже под разными пользователями... так она все равно инжектит

Андрей Антонов, [07.10.20 12:45]
Только что поигрался с открытыми двумя конфигураторами и никаких проблем не появилось.
Писал код в обоих и ни разу не выскочила эта проблема.
У меня платформа 8.3.15.1869, последний снегопат.
Запуск баз из "StartManager 1.4", а не из стандартного диалога.
Обе конфы подключаются к хранилищу, обе SQL.
Операцинка Win Server 2012 R2 Standart

Семён Павлюков, [07.10.20 12:48]
там от платформы зависит - на 17-й чаще

**Comment by artbear** [comment]
Проблема давно решена.
