### ISSUE TITLE
Странное поведение контекстной подсказки

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#41]
<b>nytlenc</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=838&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11464">Странное поведение контекстной подсказки</a>
Если стирать и заново вводить имя одной и той же переменной то почему то список контекстной подсказки задваетватся, затраивается (начинает ращростаться) и т.д.<br/>См. прикрепленную GIF анимацию.<br/>
<br/>
<b>Вложения:</b><img alt="Странное поведение снегопата.gif" src="https://snegopat.ru/forum/download/file.php?id=989&amp;sid=d281cbbb90ecad8d578a7d48c7a417d3"/>
<hr/>
<b>orefkov</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=838&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11465">Re: Странное поведение контекстной подсказки</a>
Подтверждаю, было такое несколько раз. Буду разбираться.<br/>
<br/>
<b>Вложения:</b>
<hr/>
<b>7OH</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=838&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11588">Re: Странное поведение контекстной подсказки</a>
Открыто 2 конфигуратора.<br/>В одном набираю если - подсказка появляется во втором.<br/>Выбираю конструкцию если тогда - она вставляется в первом конфиге<br/>а вот текст условия набирается во втором.<br/><br/>Страшно )<br/>
<br/>
<b>Вложения:</b><img alt="sneg_2config_01.png" src="https://snegopat.ru/forum/download/file.php?id=1022&amp;sid=d281cbbb90ecad8d578a7d48c7a417d3"/>
<hr/>
<b>nonameforme</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=838&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11592">Re: Странное поведение контекстной подсказки</a>
<div class="quotetitle">7OH писал(а):</div><div class="quotecontent">Открыто 2 конфигуратора.<br/>В одном набираю если - подсказка появляется во втором.<br/>Выбираю конструкцию если тогда - она вставляется в первом конфиге<br/>а вот текст условия набирается во втором.<br/><br/>Страшно )</div><br/><br/>Очень похоже с этим)<br/> l <a class="postlink-local" href="https://snegopat.ru/forum/viewtopic.php?p=11569#p11569">viewtopic.php?p=11569#p11569</a> l <br/><br/>Создал отдельную ветку<br/> l <a class="postlink-local" href="https://snegopat.ru/forum/viewtopic.php?f=8&amp;t=867">viewtopic.php?f=8&amp;t=867</a> l <br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
Уже исправлено. Двойников в подсказке нет.
