### ISSUE TITLE
[2.2.0.2 | 8.3.17.1549 | 14.07.20] Лишняя кавычка

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#45]
<b>progromaking</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=861&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11563">[2.2.0.2 | 8.3.17.1549 | 14.07.20] Лишняя кавычка</a>
Пример последовательности действий для воспроизведения ошибки:<br/>1. Перейти в процедуру модуля формы на сервере (например, ПриСозданииНаСервере())<br/>2. Набрать "рек", появится выпадающий список<br/>3. Из выпадающего списка выбрать "РеквизитФормыВЗначение". Подставится имя процедуры и курсор встанет между скобок<br/>4. Ввести одну двойную кавычку. При этом появится выпадающий список<br/>5. И списка выбрать слово "Объект"<br/>6. После этого подставится слово Объект, после которого будет две двойные кавычки вместо одной.<br/><br/><br/>Баг проявляется только когда два раза подряд делаем автоподстановку. <br/>Если поставить курсор между скобок процедуры "РеквизитФормыВЗначение()" и начать вводить кавычку, и выбрать слово "Объект", то баг не воспроизводится, потому что автоподстановка не вторая подряд.<br/>
<br/>
<b>Вложения:</b>

**Comment by adva-cg** [comment]
Думаю это дубль для #47

**Comment by artbear** [comment]
закрываю дубль
