### ISSUE TITLE
Ошибки при работе с кавычкой

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#47]
<b>7OH</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=846&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11485">Ошибки при работе с кавычкой</a>
[2.2.0.2 | 8.3.17.1386 | 7 июля 2020 г. 11:55:17]<br/>---<br/>Частенько при выборе типа получаем такое<br/><br/>Тип(Справочник.Номенклатура.Форма")<br/><br/>То бишь исчезает открывающая кавычка, и исчезает ещё при выборе первого слова<br/>
<br/>
<b>Вложения:</b><img alt="sneg_09_01.png" src="https://snegopat.ru/forum/download/file.php?id=998&amp;sid=d281cbbb90ecad8d578a7d48c7a417d3"/>
<hr/>
<b>orefkov</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=846&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11502">Re: Ошибки при работе с кавычкой</a>
Проверю, пока не получается воспрозвести.<br/>
<br/>
<b>Вложения:</b>

**Comment by adva-cg** [comment]
На (8.3.15.1830) стабильно воспроизводится. Причина где-то в опции "Перехват штатного списка с подсказками", т.к. без нее ошибок нет

**Comment by adva-cg** [comment]
Точнее ошибка тоже про кавычки, но чуть другая:
При нажатии кавычки открывается список выбора снегопата, и почти сразу же курсор встает перед кавычкой. После выбора типа, один курсор остается остается на этом месте, без мограний, а еще один встает после выбранного слова между двумя кавычками

**Comment by adva-cg** [comment]
Хотя если начать набирать текст, после показа списка, то ситуация как описана выше.
Отладчик показал, что в момент перехвата позиции, символ кавычки еще не вставлен. Похоже ошибка именно в этом. По хорошему, надо сначала вставить символ, а затем уже отрабатывать код в showAssistList

**Comment by adva-cg** [comment]
Уточнение по багу: проявляется, только когда набор кавычки идет при видимом окне подсказки о параметрах функции

**Comment by artbear** [comment]
Еще сценария из ишуза-дубля https://github.com/infostart-hub/snegopat/issues/45

<b>progromaking</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=861&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11563">[2.2.0.2 | 8.3.17.1549 | 14.07.20] Лишняя кавычка</a>
Пример последовательности действий для воспроизведения ошибки:<br/>1. Перейти в процедуру модуля формы на сервере (например, ПриСозданииНаСервере())<br/>2. Набрать "рек", появится выпадающий список<br/>3. Из выпадающего списка выбрать "РеквизитФормыВЗначение". Подставится имя процедуры и курсор встанет между скобок<br/>4. Ввести одну двойную кавычку. При этом появится выпадающий список<br/>5. И списка выбрать слово "Объект"<br/>6. После этого подставится слово Объект, после которого будет две двойные кавычки вместо одной.<br/><br/><br/>Баг проявляется только когда два раза подряд делаем автоподстановку. <br/>Если поставить курсор между скобок процедуры "РеквизитФормыВЗначение()" и начать вводить кавычку, и выбрать слово "Объект", то баг не воспроизводится, потому что автоподстановка не вторая подряд.<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
Выполнено в #119
