### ISSUE TITLE
Автоподключение к хранилищу

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#49]
<b>7OH</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=831&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11431">Автоподключение к хранилищу</a>
Версия репозитария : 1 июля 2020 г. 13:17:55<br/>Версия длл : 2.2.0.1 26.06.2020 16:41<br/>Платформа: 8.3.17.1386<br/>---<br/>Запускаю базу, подключенную к хранилищу<br/>Ввожу данные для подключения (пароль обычно)<br/>Скрипт (stg_autoconnect) спрашивает, подставлять ли введенные значения - жмём ДА.<br/>Ошибка<br/><div class="attachtitle">Вложение:</div><div class="attachcontent">
<img alt="Sneg_08.png" src="./download/file.php?id=974&amp;sid=d281cbbb90ecad8d578a7d48c7a417d3"/><br/>
<span class="gensmall">Sneg_08.png [ 8.3 КБ | Просмотров: 525 ]</span>
<br/>
</div><br/>При повторном входе опять появляется окно для пароля, опять вопрос, опять вылет.<br/>---<br/>Если использовать StartManager, который запускает базу с ключами подключения к хранилищу и при этом диалог подключения уже не показывается - то ошибки нет . Наверное потому, что окно подключения как раз не показывается.<br/>
<br/>
<b>Вложения:</b>
<hr/>
<b>7OH</b> <a href="https://snegopat.ru/forum/viewtopic.php?f=8&t=831&sid=d281cbbb90ecad8d578a7d48c7a417d3#p11461">Re: Автоподключение к хранилищу</a>
После обновления до 2.2.0.2 проблема пропала<br/>
<br/>
<b>Вложения:</b>

**Comment by artbear** [comment]
7OH пишет - После обновления до 2.2.0.2 проблема пропала

закрываю
