### ISSUE TITLE
Не отрабатывает loadScriptFormEpf

### ISSUE THREAD

**Issue by Shining-Phoenix** [infostart-hub/snegopat#5]
Добрый день!

Код в [репо](https://github.com/Shining-Phoenix/Snegopat-Addin-CustomAuthor)
В конструкторе SetupFormControler(файл customAuthor) не отрабатывает loadScriptFormEpf - получаю пустое значение.
Возможно дело в том что обработчики находятся не в самом объекте, а в его прототипе после преобразование в js(es3).
Дзен еще не поймал - делаю по подобию. Возможно чего-то не заимпортил или еще что.
Подскажите плз куда копать?

**Comment by kuntashov** [comment]
Какой релиз платформы используете?

**Comment by Shining-Phoenix** [comment]
8.3.16.1148

**Comment by kuntashov** [comment]
@Shining-Phoenix 

Я проверил на релизе 8.3.16.1148 в окне скрипта "Немедленное выполнение кода":

```
test_form = loadScriptFormEpf("E:\\akuntashov\\SnegopatDev\\work\\ТестоваяФормаСкрипта.epf", "Форма", SelfScript.self);
test_form.Open();
```

Форма открывается, то есть сам метод `loadScriptFormEpf` на этом релизе работает.

Но вы используете TypeScript и иерархию наследования, скорее всего как вы и предположили, проблема в JS, который получился. Сегодня посмотреть код, который получился в результате трансляции ts в js не успел посмотреть.

Приложите, пожалуйста,  js-версию скрипта (результат трансляции `ts --> js`), возможно беглый анализ js-кода позволит понять, что не так. Если не позволит, попробуем сделать минимальный скрипт на ts, на котором проблема воспроизводится, и будем уже ее отлаживать.

**Comment by Shining-Phoenix** [comment]
@kuntashov 
Обновил репо.
Как я уже писал, обработчики событий при компиляции в js ушли в родителя(prototype). Думаю дело в этом.

**Comment by Shining-Phoenix** [comment]
Наконец-то руки дошли.
Вот я гуманойд)
При вызове функции не верно указал имя формы "Форма " (пробел в конце).
Все нормально работает.
