### ISSUE TITLE
Непонятно как начинать работу с данным репозиторием и как подключать длл-ку Снегопата к этому репозиторию

### ISSUE THREAD

**Issue by artbear** [infostart-hub/snegopat#62]
я в первый раз склонировал текущий репо, до этого был внутренний, другой репо Снегопата.
и тут же впал в ступор - репо есть, куда длл-ку Снегопата положить, непонятно (

я прочел ридми, прочел руководство контрибьютора, прочел статью на ИС по развертыванию 
нет ответа.

но у меня есть опыт установки Снегопата, я быстро понял, что нужно каталог, в него положить длл-ку
далее сделать каталог core, и уже в него склонировать данный репо.

но в документации репо я этой информации не увидел.

@orefkov @kuntashov я прав и доки нет или я что-то не увидел?

если я прав, давайте, я дополню руководство контрибьютора

**Comment by kuntashov** [comment]
Документации по этому репо нет точно, дополни.
Я планировал добавить, но сразу не было времени сделать, а потом закрутилось)

**Comment by artbear** [comment]
Реализовано в 
- https://github.com/infostart-hub/snegopat/pull/65
- https://github.com/infostart-hub/snegopat/pull/61
- https://github.com/infostart-hub/snegopat/pull/66
