### ISSUE TITLE
Вылет плагина при открытии на редактирование табличного документа на форме

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#78]
Из https://snegopat.ru/new/info/e6f0a35777831b5d

Версия Снегопата: 2.0.0.3
Версия платформы 1С: 8.3.16.1224

Ошибки SessionManager.js и wndPanel.js при открытии на редактирование табличного документа, расположенного на управляемой форме. Способ воспроизведения: Настройка-Открыть https://i.imgur.com/wsbEAoH.png

    --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_events.as : void IEventConnector::fireEvent(IDispatch@, const string&inout, array<Variant>@), line 54,17 com_designer.as : void Designer::_onIdle(), line 319,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointC --- Ошибка --- Исключение AngelScript. модуль: Snegopat секция: com_windows.as функция: IMDObject@ getMdObjFromView(IFramedView@) строка: 205 1C version 8.3.16.1224. Snegopat 2.2.0.3 (16.07.2020 20:07) Exception 0xC0000005 at address 0x41703A20 in call native func QueryInterface Section: com_windows.as Function: IMDObject@ getMdObjFromView(IFramedView@) Line: 205 Callstack: com_windows.as : IV8MDObject@ IV8View::get_mdObj(), line 536,13 com_windows.as : bool IDispatch::call(int, array<Variant>&inout, Variant&out = void), line 0,13 com_designer.as : void TimerHandler::handler(uint), line 416,9 com_designer.as : void DispatchMessagesTrap_orig0(MSG&inout, uint), line 0,9 Variables: view = native object 'IFramedView' (0x5D706964) dv = native object 'IDocumentView' (0x00000000) doc = native object 'IDocument' (0x00000000) ui = native object 'IConfigMngrUI' (0x00000000) ow = native object 'IConfigMngrUIOwner' (0x00000000) pCont = native object 'IConnectionPointContainer' (0x00000000)

**Comment by artbear** [comment]
Не подтверждается. закрываю.
