### ISSUE TITLE
Ошибка запуска после обновления 24.10.2020 - 8.3.18.1128 (или 8.3.17.1745). Snegopat 2.2.0.4

### ISSUE THREAD

**Issue by tormozit** [infostart-hub/snegopat#81]
Обновился кнопкой "Обновить" в снегопате. Заодно обновил snegopat.dll на 2.2.0.4. Запускаю конфигуратор в файловой базе на платформе 8.3.18.1128 и 8.3.17.1745
и получаю ошибку
![изображение](https://user-images.githubusercontent.com/11896251/97084026-c2eadf80-161c-11eb-8457-8e689cde32e5.png)
Этот файл commands.js был обновлен в у меня в файловой системе в четверг 22.04.2020 18:19. Я его точно не редактировал.
Вернулся на snegopat.dll 2.2.0.3 - проблема ушла. 
Теперь проблема на 2.2.0.3 стала появляться.
Проверил содержимое файла commands.js . Оно у меня точно такое же как и в репозитории.
ОС Windows 10 Русский

Ниже лог
v8string__string.v       v8string__opImplConv        60 Исключение AngelScript.
         модуль: Snegopat
         секция: v8string__string.v
         функция: uint v8string__opImplConv(v8string&inout, string&inout)
         строка: 60
            1C version 8.3.18.1128. Snegopat 2.2.0.4 (22.10.2020 18:05)
         Exception 0xC0000005 at address 0x028EC75E (snegopat.dll) in call native func string::ctor
         Section: v8string__string.v
         Function: uint v8string__opImplConv(v8string&inout, string&inout)
         Line: 60
         Callstack:
           \ДђјЦ : string v8string::opImplConv() const, line 0,-128292490
           com_windows.as : void MainFrame_setTitle(ITopLevelFrame&inout, const v8string&in), line 605,5
         Variables:
           obj = native object 'v8string' (0x0019E3C4)
           ret = ??????????????’???
v8string__string.v       v8string__opImplConv        60 Bad AngelScript result code in callAs

**Comment by kuntashov** [comment]
@tormozit Сергей, перепроверь, пожалуйста, на актуальной версии скриптов из этого репозитория после вчерашнего мержа https://github.com/infostart-hub/snegopat/pull/76?

**Comment by tormozit** [comment]
@kuntashov Как это сделать, если снегопат не запускается?

**Comment by kuntashov** [comment]
@tormozit вот так:

1. Создать каталог с любым именем, например `snegopat_test`
2. Положить в него `snegopat.dll` (свой личный или от триальной версии) 
3. Открыть `cmd.exe` в этом каталоге и выполнить в нем команду `git clone https://github.com/infostart-hub/snegopat.git core`
4.  Запустить стартер Снегопата `core/starter.exe`

Это будет чистая установка на базе git-репозитория.
Если все заработает, можно попробовать из старого места установки перенести файл `data/snegopat.pfl` (каталог `snegopat_new/data/` нужно будет предварительно создать).

**Comment by KalyakinAG** [comment]
> @tormozit вот так:
> 
> 1. Создать каталог с любым именем, например `snegopat_test`
> 2. Положить в него `snegopat.dll` (свой личный или от триальной версии)
> 3. Открыть `cmd.exe` в этом каталоге и выполнить в нем команду `git clone https://github.com/infostart-hub/snegopat.git core`
> 4. Запустить стартер Снегопата `core/starter.exe`
> 
> Это будет чистая установка на базе git-репозитория.
> Если все заработает, можно попробовать из старого места установки перенести файл `data/snegopat.pfl` (каталог `snegopat_new/data/` нужно будет предварительно создать).

я так сделал, однако snegopat все равно упал, ниже лог:
com_windows.as           MainFrame_setTitle         605 Исключение AngelScript.
         модуль: Snegopat
         секция: com_windows.as
         функция: void MainFrame_setTitle(
         строка: 605
            1C version 8.3.18.1128. Snegopat 2.2.0.4 (22.10.2020 18:05)
         Exception 0xC0000005 at address 0x1391B056 in call native func ::getAdditionalTitle
         Section: com_windows.as
         Function: void MainFrame_setTitle(
         Line: 605
         Variables:
           frame = native object '' (0x0A7B2BEC)
           str = native object 'v8string' (0x0019E3C4)
           original = native object 'MainFrame_st' (0x00000000)

**Comment by kuntashov** [comment]
@orefkov @7OH посмотрите, пожалуйста, падает на 8.3.18

**Comment by artbear** [comment]
@tormozit так и не получилось запустить?

**Comment by 7OH** [comment]
Сделал как написано, на чистой установке не падает.
С копией настроек тоже не упало.

**Comment by KalyakinAG** [comment]
> Сделал как написано, на чистой установке не падает.
> С копией настроек тоже не упало.

а с подключенным локально хранилищем проверяли?

**Comment by 7OH** [comment]
С хранилищем виснет, но ошибку успел в логе поймать - такую же как в шапке.
Скрипт устанавливает заголовок и информацию должен взять о версии конфы. 
Нужна помощь Саши наверное, глянуть что не так с этим объектом.

**Comment by tormozit** [comment]
> 
> 
> @tormozit так и не получилось запустить?

Пока не пробовал.

**Comment by tormozit** [comment]
@artbear Пока не пробовал.

**Comment by tormozit** [comment]
Выложите мне готовый архив с рабочей папкой снегопата - чтобы я распаковал ее и как белый человек взял и запустил его оттуда. Настройки я осилю перенести из старой папки.

**Comment by 7OH** [comment]
Попробуй этот файлик заменить в папке v8api
У меня подвисания ушли с хранилищем
[window.zip](https://github.com/infostart-hub/snegopat/files/5470559/window.zip)

**Comment by KalyakinAG** [comment]
> Попробуй этот файлик заменить в папке v8api
> У меня подвисания ушли с хранилищем
> [window.zip](https://github.com/infostart-hub/snegopat/files/5470559/window.zip)

После замены файла конфигуратор открылся с подключенным хранилищем нормально.
Спасибо!

**Comment by PRO100MIXA** [comment]
> 
> 
> Попробуй этот файлик заменить в папке v8api
> У меня подвисания ушли с хранилищем
> [window.zip](https://github.com/infostart-hub/snegopat/files/5470559/window.zip)

Мне тоже помогло, спасибо

**Comment by artbear** [comment]
выполнено. закрываю.
