### ISSUE TITLE
При запуске get_latest ошибка "runk не является внутренней или внешней командой"

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/snegopat#82]
Запускаю `get_latest`, скрипт начинает выполняться и останавливается с ошибкой ` "runk не является внутренней или внешней командой"`.

Запускаю второй раз, все обновляется успешно.

Снегопат: 2.2.0.4

**Comment by orefkov** [comment]
С get_latest пока всё сложно. В гитовом репо он не должен использоваться, обновлять средствами гит. То есть его нужно запускать в репо, подключенном к старому репо на snegopat.ru. Смешивать нельзя.
Можешь подробнее расписать, как используешь его.

**Comment by kuntashov** [comment]
@orefkov у меня ошибка была в репо fossil, гитхабовский репо так не обновлял.

**Comment by kuntashov** [comment]
> Можешь подробнее расписать, как используешь его.

У меня две инсталляции Снегопата - с гитхаба, сделанная по инструкции разработчика здесь в репо, в ней только разработку веду. Вторая - для основной работы, которая получена "классически" (скачан стартовый пакет и dll с сайта). Ее использую в работе.

Вот в основной "классической" инсталляции как раз захотел обновиться после твоих последних правок для 8.3.18 и получил такую ошибку. Причем судя по тексту сообщений в консоли репо обновился, но ошибка все равно произошла.

Потом запустил get_latest второй раз и выдало сообщение, что все успешно обновилось.

**Comment by kuntashov** [comment]
Скриншот ошибки от пользователя из чата https://t.me/snegopat_chat/5132
 
![photo_2020-10-26_15-21-19](https://user-images.githubusercontent.com/1042299/97166861-5a783b80-179f-11eb-8ca8-b4ea7f4aafb2.jpg)

**Comment by kuntashov** [comment]
100% проблема воспроизводится только при обновлении уже ранее существовавшей старой инсталляции, в которой у `get_latest` вызывается `fossil update` и этот вызов привозит новую версию скрипта, в которой эта команда выглядит как `fossil update trunk`.

Звучит фантастично, но выглядит так что в момент выполнения `fossil update` осуществляется обновление скрипта из репозитория и как-будто cmd.exe переключается на интерпретацию уже новой версии скрипта `get_latest` и как раз начиная с части имени ветк - "runk".

К сожалению, не знаю нюансов, как работает командный интерпретатор windows.

**Comment by kuntashov** [comment]
> Звучит фантастично, но выглядит так что в момент выполнения fossil update осуществляется обновление скрипта из репозитория и как-будто cmd.exe переключается на интерпретацию уже новой версии скрипта get_latest и как раз начиная с части имени ветк - "runk".

Невероятно, но это так!

Провел такой эксперимент:

Создал скрипт
```bat
@echo off

echo 1
echo 2

pause

echo 3
echo 4
```
Запустил его.
Скрипт вывел 
````
1
2
Для продолжения нажмите любую клавишу . . .
```

Пока скрипт остановился на паузе я сделал его копию и переписал скрипт вот так:

```bat
@echo off

echo 1
echo 2

pause

echo 5
echo 6
```
И полученной копией перезаписал запущенный файл.

В окне консоли, где скрипт остановился на паузе нажал `Enter`, скрипт продолжил выполнение и вывел

````
5
6
```

В общем, судя по всему `cmd.exe` обрабатывает пакетный файл построчно и с каждой строкой cmd-файл перечитывается.

Таким образом, чтобы починить ошибку, `get_latest` должен при своем запуске куда-то себя копировать и запускать свою копию, чтобы при перезаписи во время обновления его исходный код не менялся на лету.

Тем не менее, проблема ничтожна, решать ее, вероятно, не имеет смысла, лучше сосредоточиться на реализации новой схемы дистрибуции Снегопата.

**Comment by artbear** [comment]
уже выполнено.
