### ISSUE TITLE
Авто аутентификация при работе с хранилищем конфигурации для расширения конфигурации

### ISSUE THREAD

**Issue by malikov-pro** [infostart-hub/snegopat#93]
**Существует проблема**
При использовании хранилища конфигурации для расширений отсутствует авто аутентификация

**Хотелось бы иметь следующую функциональность**
Авто аутентификацию аналогичную работе скрипта "stg_autoconnect"

**Comment by 7OH** [comment]
Надо изменить "немного" скрипт.
Окна ловятся - caption почти такой же, но расширений может быть несколько, потому надо немного изменить логику хранения данных.
Попробую

**Comment by malikov-pro** [comment]
Обновил вручную модуль, почистил настройки, добавил хранилища к двум расширениям с паролем, перезапустил, аутентификацию прошло успешно.
